version: '3.7'
services:
  postgresdb:
    image: postgres:10.5
    container_name: postback
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql/populate.sql:/docker-entrypoint-initdb.d/populate.sql

  restapp:
    image: restapp:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/postgres
    restart: on-failure
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgresdb

  front:
    image: front:latest
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - postgresdb