create table products
(
    id          integer generated by default as identity
        primary key,
    amount      bigint,
    code        uuid
        constraint uk_57ivhy5aj3qfmdvl6vxdfjs4p
            unique,
    description varchar(255),
    type        varchar(255),
    value       numeric(19, 2)
);

create table stock_movements
(
    id         integer generated by default as identity
        primary key,
    amount     bigint  not null,
    date       timestamp,
    movement   varchar(255),
    sale_value numeric(19, 2),
    product_id integer not null
        constraint fkjcaag8ogfjxpwmqypi1wfdaog
            references products
);